### PR TITLE
add hebrew translation

### PR DESCRIPTION
**Pull request by electriquo**

### CODE REVIEW

**Comment by electriquo** [comment]
@rumboalla thank you for the app! as appreciation, i hope this small contribution would assist in getting more traction :)

**Comment by rumboalla** [comment]
Cheers

**Comment by electriquo** [comment]
@rumboalla why did the build failed? anything is can do to fix?

**Comment by rumboalla** [comment]
> @rumboalla why did the build failed? anything is can do to fix?

Some languages require more plurals to be added for specific cases.

/home/runner/work/apkupdater/apkupdater/app/src/main/res/values-he/strings.xml:65: Error: For locale "he" (Hebrew) the following quantity should also be defined: two [MissingQuantity]

```
<plurals name="notification_update_description">
        <item quantity="zero">לא נמצאו עדכונים.</item>
        <item quantity="one">נמצאו %1$d עדכונים.</item>
        <item quantity="other">נמצאו %1$d עדכונים.</item>
    </plurals>
```

**Comment by electriquo** [comment]
i fixed the "one" for better readability and added "two".

```xml
<plurals name="notification_update_description">
        <item quantity="zero">לא נמצאו עדכונים.</item>
        <item quantity="one">נמצא עדכון.</item>
        <item quantity="two">נמצאו 1$d עדכונים.</item>
        <item quantity="other">נמצאו 1$d עדכונים.</item>
</plurals>
```
i hope this will fix the build process. if it is not hard for you, would appreciate if you could incorporate the changes. otherwise, please do tell and i will open a PR.

**Comment by HazakuraID** [comment]
what hell. there any wrong code  %1$ is not used when typo 1$ letter "d" I don't know translation mistakes you learn.

Try to see your eyes are really focused right now its ( %1$d ) 🤦🏻‍♂️
Edit: forget that % number.

**Comment by HazakuraID** [comment]
@rumboalla answered correctly it's a case of writing: 1$d

**Comment by electriquo** [comment]
guys, hebrew is right-to-left language. when it is mixed with left-to-write language, the console rendering might not display it correctly. it should be from right-to-left: number then the text.

> what hell. there any wrong code %1$ is not used when typo 1$ letter "d" I don't know translation mistakes you learn.
> Try to see your eyes are really focused right now its ( 1$d )

in the original code, it is different https://github.com/rumboalla/apkupdater/blob/db0e7932690b53c5ff53782f267efba0413b7cd4/app/src/main/res/values/strings.xml#L67

if you will render the following from right to left (github renders it incorrectly), it should be as follows

```text
1$d עדכונים נמצאו
```

reminding you that it was open for a review, but thank you for being nice :)

i also took the care to fix the snippet in https://github.com/rumboalla/apkupdater/pull/480#issuecomment-1797030341.

> i hope this will fix the build process. if it is not hard for you, would appreciate if you could incorporate the changes. otherwise, please do tell and i will open a PR.

@rumboalla your answer please?

**Comment by rumboalla** [comment]
Should be fixed now, thanks

**Pull request merged**
