### PR TITLE
Updated new translation values-ms

### PR DESCRIPTION
**Pull request by HazakuraID**
Suggestions added to Malay both same Indonesian. Them because I come from Sumatra and speak with Indonesia-Malay.

Terima kasih.

### CODE REVIEW

**Comment by rumboalla** [comment]
Cheers

**Comment by HazakuraID** [comment]
Screenshot_2023_1103_143145
@rumboalla hey I'm sorry wrong file folder typo changed for values-ms/strings.xml error.
Screenshot_2023_1103_143505

**Comment by HazakuraID** [comment]
I was deliberately forgiven for being late this morning unfortunately.

**Comment by rumboalla** [comment]
Fixed now

**Pull request merged**
