### PR TITLE
Update GitHubApp.kt

### PR DESCRIPTION
**Pull request by Blurazzle**
Added breezyweather and olauncher.

### CODE REVIEW

**Comment by rumboalla** [comment]
Sorting

**Comment by Blurazzle** [comment]
@rumboalla Not sure what you meant, but I have sorted the list alphabetically :).

**Comment by rumboalla** [comment]
Please keep the same sorting (app name and not package name).

**Comment by Blurazzle** [comment]
Hey, is this version better?

Using "Breezy Weather" seems a bit challenging (ref: [Breezy Weather v5.2.7](https://github.com/breezy-weather/breezy-weather/releases/tag/v5.2.7)). It might be best to pick the standard option, but I'm not sure if it's possible with the current regex. For example, would something like contains("breezy-weather-*_standard") work? This is why I picked the freenet version. The freenet version only fetches data from openssource data sources.

**Pull request merged**
