### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
As [discussed here](https://github.com/rumboalla/apkupdater/issues/27#issuecomment-1676470714). Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this (replacing screenshots, adding a featureGraphic and maybe also per-release changelogs, more locales – whatever suits you).

### CODE REVIEW

**Comment by rumboalla** [comment]
Cheers!

**Comment by IzzySoft** [comment]
Just as a note: Removing the HTML means removing the formatting. So just for clarification: What format do you plan to use in the future? Currently it's a single paragraph, which can be "anything". Will you keep it compatible with "standard Markdown"? Or should it be treated as "plain text" (looks a bit ugly then)? Or will you return to HTML (the "compression" into a single line is done to prevent fdroidserver/fdroidclient from inserting additional `<br>` for each `\n`, but that would be done by my updater than – only in my repo of course)?

**Comment by IzzySoft** [comment]
Oh, and you do not want to list the supported sources with the app's description?

**Comment by rumboalla** [comment]
I'll change it to markdown then

**Comment by IzzySoft** [comment]
Thanks, marked (ugh, I mean adjusted the config on my end accordingly).

**Pull request merged**
