### PR TITLE
Added: 2 GitHub app flavors, Changed: 1 app ID

### PR DESCRIPTION
**Pull request by DarkCrypt**
Added: Foss flavor for [Amarok-Hider](https://github.com/deltazefiro/Amarok-Hider/blob/main/app/build.gradle) and [Delta-Icons](https://github.com/Delta-Icons/android/blob/master/app/build.gradle).
Changed: App ID for [SoulSearching](https://github.com/enteraname74/SoulSearching/releases/tag/v0.2.3).

Flavors can only be added if there's a ".suffix" correct? How can we add flavors when they have the same app ID?

### CODE REVIEW

**Comment by AnonymousWP** [comment]
Honestly starting to wonder what the point is of all these extra apps being added while it seems a new build is not going to be released anytime soon since November.

**Comment by DarkCrypt** [comment]
Are you trying to tell me that the present build of ApkUpdater won't provide updates for these added apps without a new release?

**Comment by AnonymousWP** [comment]
According to the changelog of releases, it seems like that: https://github.com/rumboalla/apkupdater/releases/tag/3.0.2

> GitHub source: Added sdmaid, spotube, trackworktime

**Comment by maj113** [comment]
Well maybe apkupdater could pull a db of apps from this repo instead of being hardcoded inside the app itself

**Comment by DarkCrypt** [comment]
Interesting, I agree with you both. It would also be a good idea to do this for other sources that require manual app additions like GitLab, Codeberg, etc.

I was going to attempt to add flavors since I failed to do so while adding apps in previous PR's. Instead I'll refrain from any future additions until we here word from rumboalla.

**Comment by rumboalla** [comment]
This is a very good idea, I added it to the list.

**Pull request merged**
