### PR TITLE
Add revanced YT and YT-M

### PR DESCRIPTION
**Pull request by Youngei402tw**
Add revanced youtube and revanced youtube music by NoName-exe

### CODE REVIEW

**Comment by Jvr2022** [comment]
hi, I added this to my own changes because I was already adding 100 new apps and if this were to be merged I would have to start over @Youngei402tw

**Comment by Youngei402tw** [comment]
> hi, I added this to my own changes because I was already adding 100 new apps and if this were to be merged I would have to start over @Youngei402tw 

No problem. You do you, I just wanna add the two apps into the list

**Comment by Jvr2022** [comment]
done

**Comment by Jvr2022** [comment]
#527

**Comment by rumboalla** [comment]
Closing since this was added in #527

**Pull request closed without merging**
