### PR TITLE
Added: 138 GitHub apps, Changed: 2 GitHubUser names, Resorted List

### PR DESCRIPTION
**Pull request by DarkCrypt**
Added: 121 GitHub apps.
Changed: 1 GitHubUser name; "vector-im" -> "element-hq". See [vector-im](https://github.com/vector-im) for reference.
Resorted List

### CODE REVIEW

**Comment by TotallyAvailable** [comment]
Arcticons is about to be moved - https://github.com/Donnnno/Arcticons/issues/1799

And given your addition of the whole set of SMT, https://github.com/FossifyOrg is about to be released if you feel like adding those as well.

**Comment by DarkCrypt** [comment]
Thank you for the info.

I changed Arcticons to try to reflect this move so right now the package name could be wrong.

I added all 17 FossifyOrg apps. There are 6 package names that they still need to change in their repos. I also tried to reflect these upcoming changes.

Sounds like SMT may bomb soon, might be deleting these from the list sometime(?)

(Total apps = 282)

**Comment by TotallyAvailable** [comment]
As all 4 versions are now Reproducible on F-Droid, the packageid is probably going to stay as 'com.donnnno.arcticons'.
Given that the 4 flavors are attached to 1 GitHub release I'm not sure if it's even going to work like this without additional regex filtering.

~Assuming the filter can handle more than 1 set of contains/notcontains~ the other 3 flavors could also be included.

Just going by the existing keepass2android entry, as each file is clearly labeled this should work ? Assuming it does, the existing Arcticons entry needs a
```
, contains("normal")
```
as well.
```
GitHubApp("com.donnnno.arcticons.you", "Arcticons-Team", "Arcticons", contains("you")),
GitHubApp("com.donnnno.arcticons.light", "Arcticons-Team", "Arcticons", contains("black")),
GitHubApp("com.donnnno.arcticons.daynight", "Arcticons-Team", "Arcticons", contains("dayNight")),
```
- https://github.com/Donnnno/Arcticons/releases/tag/8.3.1

```
GitHubApp("com.mirfatif.mylocation", "mirfatif", "MyLocation"),
GitHubApp("com.aistra.hail", "aistra0528", "Hail"),
GitHubApp("app.simple.peri", "Hamza417", "Peri"),
```
There are so many more I would add...given that most of them provide full/lite/foss/market/libre/armv7&v8 versions with the same package name that's obviously not on me to decide which version a user of APKUpdater is supposed to use.
Breaking installations or causing issues is not something I want to do.

If I come across more potential (single version) inclusions the next time I manually hunt for updates, I'll add them.

**Comment by rumboalla** [comment]
> As all 4 versions are now Reproducible on F-Droid, the packageid is probably going to stay as 'com.donnnno.arcticons'. Given that the 4 flavors are attached to 1 GitHub release I'm not sure if it's even going to work like this without additional regex filtering.
> 
> ~Assuming the filter can handle more than 1 set of contains/notcontains~ the other 3 flavors could also be included.
> 
> Just going by the existing keepass2android entry, as each file is clearly labeled this should work ? Assuming it does, the existing Arcticons entry needs a
> 
> ```
> , contains("normal")
> ```
> 
> as well.
> 
> ```
> GitHubApp("com.donnnno.arcticons.you", "Arcticons-Team", "Arcticons", contains("you")),
> GitHubApp("com.donnnno.arcticons.light", "Arcticons-Team", "Arcticons", contains("black")),
> GitHubApp("com.donnnno.arcticons.daynight", "Arcticons-Team", "Arcticons", contains("dayNight")),
> ```
> 
This should work as long as the package names are different.

> * https://github.com/Donnnno/Arcticons/releases/tag/8.3.1
> 
> ```
> GitHubApp("com.mirfatif.mylocation", "mirfatif", "MyLocation"),
> GitHubApp("com.aistra.hail", "aistra0528", "Hail"),
> GitHubApp("app.simple.peri", "Hamza417", "Peri"),
> ```
> 
> There are so many more I would add...given that most of them provide full/lite/foss/market/libre/armv7&v8 versions with the same package name that's obviously not on me to decide which version a user of APKUpdater is supposed to use. Breaking installations or causing issues is not something I want to do.
> 
> If I come across more potential (single version) inclusions the next time I manually hunt for updates, I'll add them.

If the file names are tagged with the architecture, the app will try to match it.

**Comment by DarkCrypt** [comment]
@TotallyAvailable 
Thank you for your help again!

I didn't consider other flavors when I was adding apps. I'll go back through the list and include any if necessary.

**Pull request merged**
