### PR TITLE
Update changed Letter word README.md

### PR DESCRIPTION
**Pull request by HazakuraID**
Make better different its without language changes from letter word.

### CODE REVIEW

**Comment by rumboalla** [comment]
``Italian, Indonesian, Malay, Korean,`` this doesn't seem to be properly sorted.

**Comment by HazakuraID** [comment]
Ah i forgot it sorted for typo Korea and Malay changed letter fix.

I think It maybe sorted different Italian same Europe and asia Indonesian

**Comment by HazakuraID** [comment]
See: same is sorted try it again [Readme forks](https://github.com/HazakuraID/apkupdater/blob/3.x/README.md#support-language-in-available)

**Comment by HazakuraID** [comment]
No approved or can as closed?
Is it still a long time online but not too late on weekdays.

**Pull request closed without merging**
